language: node_js
node_js:
  - 12

services:
  - docker

script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed joelzeal/udagram-api-feed

  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user joelzeal/udagram-api-user

  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend joelzeal/udagram-frontend

  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy joelzeal/udagram-reverseproxy

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push joelzeal/udagram-api-feed
  - docker push joelzeal/udagram-api-user
  - docker push joelzeal/udagram-frontend
  - docker push joelzeal/udagram-reverseproxy

